### ISSUE TITLE
Shader not working

### ISSUE THREAD

**Issue by alchem1no** [cgytrus/MenuShaders#12]
There's a shader I like a lot but it doesn't work for some reason. Maybe it has textures, I don't know where I can find if a shader uses one or not.
[menu-shader.zip](https://github.com/user-attachments/files/16227602/menu-shader.zip)

**Comment by cgytrus** [comment]
use the new built-in shadertoy compatibility by just pasting the code from shadertoy directly into menu-shader.fsh. do not use tning's shadertoy porter as its very unreliable
