### ISSUE TITLE
what does it mean by "menu-shader.fsh"

### ISSUE THREAD

**Issue by Button-Pushing** [cgytrus/MenuShaders#13]
the title explains itself - I'm confused.

**Comment by cgytrus** [comment]
read the first line of the usage section. you have to create a texture pack with a file with that name
here is how to create such a file https://answers.microsoft.com/en-us/windows/forum/all/how-do-i-make-a-new-file-with-my-own-extension-in/9142b57d-919c-47f7-a623-a7df4faa7ea1
