### ISSUE TITLE
Custom Shader doesn't work on main menu but does on every other screen

### ISSUE THREAD

**Issue by Fraa4** [cgytrus/MenuShaders#15]
![20240904002404_1](https://github.com/user-attachments/assets/44e37bcd-3c84-4e92-856b-d8e306e299c9)
![20240904002406_1](https://github.com/user-attachments/assets/0a1f645f-6046-46a9-a012-0ff57ece87f4)
I don't really know what is wrong, i followed the tutorial on the geode page and created menu-shader.fsh on the texture pack folder

**Comment by cgytrus** [comment]
you have geodify installed. disable/remove it completely or use its settings menu to disable it for menus you want to see menu shaders in.
