### ISSUE TITLE
Causes Log Spam

### ISSUE THREAD

**Issue by ghost** [cgytrus/MenuShaders#17]
These same 4 lines are printed over and over again:
```
17:53:32 WARN  [Main] [Menu Shaders]: failed to find node with id 'define REVERSE_PATTERN'
17:53:32 WARN  [Main] [Menu Shaders]: failed to find node with id 'define SHOW_GRID'
17:53:32 WARN  [Main] [Menu Shaders]: failed to find node with id 'define SHOW_VERTICES'
17:53:32 WARN  [Main] [Menu Shaders]: failed to find node with id 'define BUMP'
```
I'll attach the full log file:
[Geode 2024-09-24 17.53.18.log](https://github.com/user-attachments/files/17110462/Geode.2024-09-24.17.53.18.log)

**Comment by cgytrus** [comment]
dont think theres anything that can be done here without changing the mod's advanced api (that, admittedly, probably nobody uses, but it exists so i would rather not break it)
as a workaround you can simply erase the 4 lines in the shader file that would cause these: `//#define REVERSE_PATTERN`, `//#define SHOW_GRID`, `//#define SHOW_VERTICES`, `//#define BUMP`. theyre just comments so removing them is completely safe

**Comment by ghost** [comment]
Ah, sure thing, thanks!
