### ISSUE TITLE
Shader brightness is odd

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [cgytrus/MenuShaders#18]
my shader is really dark and I would like to fix it.
the shader -  [menu-shader.zip](https://github.com/user-attachments/files/17171537/menu-shader.zip)

**Comment by N0VA-The-Git-User** [comment]
![image](https://github.com/user-attachments/assets/bfd1e8e5-7bee-4da9-8b42-262e94136072)

**Comment by cgytrus** [comment]
this is an issue tracker for the mod itself, please dont create issues explicitly asking to fix your shader for you. you can create a support forum post on the geode discord and ping me there

**Comment by N0VA-The-Git-User** [comment]
Oh, okay👍
