### ISSUE TITLE
Mod not working for geode 2.0

### ISSUE THREAD

**Issue by masckmaster2007** [cgytrus/MenuShaders#4]
Tried to build it myself... Needs some modification :|
![image](https://github.com/cgytrus/MenuShaders/assets/63162857/0e7f46b1-a869-4cf6-826a-2372a4cc1219)

**Comment by RoootTheFox** [comment]
the mod isn't updated for 2.2 yet - see #3 for my updating progress

**Comment by cgytrus** [comment]
the pr has been merged 🎉
