### ISSUE TITLE
Custom shaders not working at all

### ISSUE THREAD

**Issue by vp999S** [cgytrus/MenuShaders#5]
Custom shaders loaded using geode's texture loader do not work at all and defaults to the original scrolling main menu. I tried using a bunch of shaders that worked previously on the 2.1 version of the mod and all lead to the same result.

### ~~Maintainer's edit: see [this](https://github.com/cgytrus/MenuShaders/issues/5#issuecomment-2131275550) response, this will likely fix your issue.~~

**Comment by cgytrus** [comment]
please, attach log files as well as the shader files.

**Comment by BombVR1** [comment]
> please, attach log files as well as the shader files.

same is happening to me, i even used the ones from the x thread, they dont work, also how do i check the logs?

**Comment by cgytrus** [comment]
right click the game in steam > properties > browse local files > go to geode/logs and send the log from the session with menu shaders (if you dont know which ones those are, open the game, select the texture pack with one of the broken shaders, go to the main menu, close the game and send latest.log)

**Comment by BombVR1** [comment]
> right click the game in steam > properties > browse local files > go to geode/logs and send the log from the session with menu shaders (if you dont know which ones those are, open the game, select the texture pack with one of the broken shaders, go to the main menu, close the game and send latest.log)

ok i will

**Comment by BombVR1** [comment]
> right click the game in steam > properties > browse local files > go to geode/logs and send the log from the session with menu shaders (if you dont know which ones those are, open the game, select the texture pack with one of the broken shaders, go to the main menu, close the game and send latest.log)
[Geode 2024-05-17 14.55.58.log](https://github.com/cgytrus/MenuShaders/files/15350445/Geode.2024-05-17.14.55.58.log)
hope that helps
if you need another:
[Geode 2024-05-17 15.00.57.log](https://github.com/cgytrus/MenuShaders/files/15350457/Geode.2024-05-17.15.00.57.log)
im using:
[myshader.zip](https://github.com/cgytrus/MenuShaders/files/15350494/myshader.zip)

**Comment by vp999S** [comment]
> please, attach log files as well as the shader files.

[Geode 2024-05-17 20.58.27.log](https://github.com/cgytrus/MenuShaders/files/15355380/Geode.2024-05-17.20.58.27.log)
[menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15355384/menu-shader.zip)

**Comment by cgytrus** [comment]
@cute-funny-cats-meow looks like your shader uses textures, those are unsupported by menu shaders, as stated in the FAQ of the porter website.

**Comment by cgytrus** [comment]
> > please, attach log files as well as the shader files.
> 
> [Geode 2024-05-17 20.58.27.log](https://github.com/cgytrus/MenuShaders/files/15355380/Geode.2024-05-17.20.58.27.log) [menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15355384/menu-shader.zip)

looks like this shader has an error in its code, are you sure it works in 2.1?
![image](https://github.com/cgytrus/MenuShaders/assets/30120687/6f49f151-a78e-42cc-9a17-3de7fca0934c)

works fine after fixing the shader code: [menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15355687/menu-shader.zip)
![image](https://github.com/cgytrus/MenuShaders/assets/30120687/911fdf07-aa51-431b-b42f-c3513f2b9cff)

**Comment by BombVR1** [comment]
> @cute-funny-cats-meow looks like your shader uses textures, those are unsupported by menu shaders, as stated in the FAQ of the porter website.

how do i check if they have textures?

**Comment by copycold** [comment]
doesn't work with anything that i try either, this one shouldn't use textures as it's just triangles. maybe it's something about the porter? keeps coming up with the "failed to create shader node" error

also the success log is when i removed the shader from the resources folder

[Geode 2024-05-19 07.01.37.log](https://github.com/cgytrus/MenuShaders/files/15368180/Geode.2024-05-19.07.01.37.log)

[menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15368178/menu-shader.zip)

**Comment by cgytrus** [comment]
> doesn't work with anything that i try either, this one shouldn't use textures as it's just triangles. maybe it's something about the porter? keeps coming up with the "failed to create shader node" error
> 
> also the success log is when i removed the shader from the resources folder
> 
> [Geode 2024-05-19 07.01.37.log](https://github.com/cgytrus/MenuShaders/files/15368180/Geode.2024-05-19.07.01.37.log)
> 
> [menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15368178/menu-shader.zip)

as the error directly above the one you mentioned says, there are 2 errors in the shader itself.

**Comment by RueOfficial** [comment]
My shader's dont work as well, i dont think they have textures from what ive seen but they just default to the default gd screen instead of displaying the shader

Logs: 
[Geode 2024-05-19 22.38.02.log](https://github.com/cgytrus/MenuShaders/files/15372472/Geode.2024-05-19.22.38.02.log)

Shader File:
[menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15372475/menu-shader.zip)

**Comment by copycold** [comment]
it managed to work for me when i used a plasma shader so probably if you use a simple shader it will work

**Comment by RueOfficial** [comment]
i wanted this shader specifically it looked extremely cool, rip

**Comment by cgytrus** [comment]
> it managed to work for me when i used a plasma shader so probably if you use a simple shader it will work

this has nothing to do with the shaders' complexity. you just got lucky the shader developer wrote their code in a way that made your specific gpu driver happy.

**Comment by cgytrus** [comment]
closing as the issue of the OP has been resolved and i will not continue fixing others' shaders for everyone.

**Comment by Naxrin** [comment]
> > please, attach log files as well as the shader files.
> 
> [Geode 2024-05-17 20.58.27.log](https://github.com/cgytrus/MenuShaders/files/15355380/Geode.2024-05-17.20.58.27.log) [menu-shader.zip](https://github.com/cgytrus/MenuShaders/files/15355384/menu-shader.zip)

**The solution to your issue:**
Open your fsh file, go to Line 81 (or nearby?), it says:
*	vec2 uv = gl_FragCoord/resolution.xy;*
You edit it to
*	vec2 uv = gl_FragCoord.xy/resolution.xy;*
Save the file and refresh to any game menu with menu-shaders ON, Then your shader will work:
![image](https://github.com/cgytrus/MenuShaders/assets/94737247/cf648ad6-c0e8-40cb-9904-c34999c7e545)

**Comment by Fryy55** [comment]
If anyone sees this with their shaders not working, see if this helps. You'll very likely have "vec2 uv = gl_FragCoord/resolution.xy;" right in the beginning of your main function in a menu-shader.fsh file. Change that to "vec2 uv = gl_FragCoord.xy/resolution.xy;" as it might fix your issue.
![image](https://github.com/cgytrus/MenuShaders/assets/160249433/9596ed7f-d4c1-45e3-8cb0-8156a2ad8f07)

**Comment by cgytrus** [comment]
i looked into it further, the shadertoy porter everyone's using has always been broken, and it only started manifesting now, either after driver updates or changing the glsl version, even tho implicit casts have always been forbidden by the [glsl spec](https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.1.10.pdf) (see: page 16, or 22 in the pdf itself). to fix this, replace all instances of `gl_FragCoord` that dont have `.xy` after them with `gl_FragCoord.xy`, as Fryy55 mentioned

**Comment by Tamarindo-XD** [comment]
Shader problem

**Comment by Tamarindo-XD** [comment]
[menu-shader.zip](https://github.com/user-attachments/files/16075139/menu-shader.zip)
Shader problem

**Comment by Tamarindo-XD** [comment]
I already put the new code for the shader but now I get the light blue background and it goes down slightly to blue.
